Repository Thoth2023/thoth-remake, pull requests merged in 2024-06, with the labels that each got.

#255 Bug/224@caixa de selecao copy planning
  app/Http/Controllers/ProjectController.php
  app/Http/Requests/Project/ProjectStoreRequest.php
  app/Models/Project.php
  composer.json
  composer.lock
  lang/en/project/create.php
  lang/pt_BR/project/create.php
  resources/views/projects/create.blade.php
Labels: enhancement

#262 257 internacionalizao
  app/Http/Controllers/HomeController.php
  app/Http/Controllers/LoginController.php
  lang/en/auth/login.php
  lang/en/nav/topnav.php
  lang/en/pages/add_member.php
  lang/en/project/edit.php
  lang/en/project/planning.php
  lang/pt_BR/auth/login.php
  lang/pt_BR/nav/topnav.php
  lang/pt_BR/pages/add_member.php
  lang/pt_BR/project/edit.php
  lang/pt_BR/project/planning.php
  resources/views/components/fixed-plugin.blade.php
  resources/views/components/help-modal.blade.php
  resources/views/components/helpers/modal.blade.php
  resources/views/layouts/navbars/auth/topnav.blade.php
  resources/views/layouts/navbars/guest/navbar.blade.php
  resources/views/livewire/planning/quality-assessment/quality-score.blade.php
  resources/views/project/conducting/index.blade.php
  resources/views/project/planning/index.blade.php
  resources/views/project/reporting/index.blade.php
  resources/views/projects/add_member.blade.php
  resources/views/projects/edit.blade.php
  resources/views/projects/index.blade.php
  resources/views/projects/search-project.blade.php
  resources/views/projects/show.blade.php
  routes/web.php
Labels: i18n

#273 refactor: :recycle: Refatoração da autorização de project
  app/Http/Controllers/ProjectController.php
  app/Models/Project.php
Labels: enhancement

#275 Correção da internacionalização
  app/Livewire/Planning/QualityAssessment/QualityScore.php
  app/Livewire/Planning/QualityAssessment/Question.php
  lang/en/project/planning.php
  lang/pt_BR/project/planning.php
  resources/views/projects/index.blade.php
Labels: bug, i18n

#277 Correção das páginas
  database/migrations/2024_06_07_000256_remove_bcrypt.php
  lang/en/auth/register.php
  lang/en/pages/home.php
  lang/pt_BR/auth/register.php
  lang/pt_BR/pages/home.php
  resources/views/auth/register.blade.php
  resources/views/layouts/app.blade.php
  resources/views/pages/help.blade.php
Labels: enhancement, design

#282 Bug/281@copy planning edit project
  app/Http/Controllers/ProjectController.php
  lang/en/project/edit.php
  lang/pt_BR/project/edit.php
  resources/views/projects/edit.blade.php
Labels: bug, enhancement

#291 ENHANCEMENT - Tela Termos e Condições
  app/Http/Controllers/TermsController.php
  lang/en/pages/terms.php
  lang/pt_BR/pages/terms.php
  resources/views/auth/register.blade.php
  resources/views/pages/terms.blade.php
  routes/web.php
Labels: enhancement

#301 fix: :art: Inseridos os campos de Firstname, Lastname e Institution n…
  app/Http/Controllers/RegisterController.php
  lang/en/auth/register.php
  lang/en/pages/profile.php
  lang/pt_BR/auth/register.php
  lang/pt_BR/pages/profile.php
  resources/views/auth/register.blade.php
  resources/views/pages/user-profile.blade.php
Labels: refactor, accessibility

#312 Refatoração da autorização e internacionalização em create project e meus projetos
  app/Http/Controllers/ProjectController.php
  app/Models/Project.php
  resources/views/projects/create.blade.php
  resources/views/projects/index.blade.php
Labels: enhancement, i18n
